# Chassis Configuration
#
# This file is the default configuration for all projects. The fallback order of
# configuration files is:
#
# - project/content/config.local.yaml   (project-specific overrides)
# - project/content/config.yaml         (project-specific defaults)
# - project/config.local.yaml          (global overrides)
# - project/config.yaml                 (global defaults)

# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
    - vagrant.local

# IP address to use on the private network
#
# DHCP is used by default to assign IP addresses dynamically, override only if
# you need a static IP for your box.
#
# Values: "dhcp", or any valid IP
ip: dhcp

# Should we use multisite?
# (Only subdirectories are supported currently)
# Values: Yes, No
multisite: No

# Database configuration
# (When overriding, include all values)
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword

# Admin configuration
# (When overriding, include all values)
admin:
    user: admin
    email: admin@example.com
    password: password

# WordPress directory
# (This is usually `wp`, unless you're transplanting Chassis into
# an existing project)
wpdir: wp

# PHP version
# Values: 5.3, 5.4, 5.5 (or e.g. 5.3.3)
php: 5.4
